# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: elasticbeanstalk-badger # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: go1.x

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  getBadge:
    handler: bin/getBadge
    #per function IAM Role per best practive
    iamRoleStatementsName: elasticbeanstalk-badger-describe-environments-lambda #optional custom role name setting instead of the default generated one
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - elasticbeanstalk:DescribeEnvironments
        Resource: "arn:aws:elasticbeanstalk:${self:provider.region}:*"
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: getBadge/{environmentId}
          method: get
          cors: true
          request:
            parameters:
              paths:
                environmentId: true

plugins:
  - serverless-iam-roles-per-function
  - serverless-apigw-binary
custom:
  apigwBinary:
    types:           #list of mime-types
      - 'image/svg+xml'
